# Generated by Django 2.2 on 2022-03-02 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register',
            new_name='registration',
        ),
    ]
